### ISSUE TITLE
It started to give CORS error.

### ISSUE THREAD

**Issue by anil-turk** [ashishagarwal2023/freegpt.js.org#1]

**Comment by devashish2024** [comment]
No issue to me? 
![image](https://github.com/ashishagarwal2023/freegptjs/assets/83082760/eb2a773c-6f5e-41ad-bbd2-5e6cf660a1db)

test at: https://freegpt.js.org/example.html

**Comment by devashish2024** [comment]
@anil-turk Actually you might not be able to fetch from there from http, try the same thing on a delpoyment (Https)

**Comment by anil-turk** [comment]
Yes it fixed. Maybe there was a protection mode was active. Because I was tried 30 prompts one after another.

**Comment by anil-turk** [comment]
Can we do it with node. I tried other projects, but it doesn't work well as this.I tried but I couldnt scrape from you.com

**Comment by devashish2024** [comment]
I already said this in README. The site is protected by Cloudflare and you cannot easily scrape it.

Consider just running this script on the client-side I know there are limits.

**Comment by devashish2024** [comment]
> Yes it fixed. Maybe there was a protection mode was active. Because I was tried 30 prompts one after another.

It wasn't a issue.
