### ISSUE TITLE
The sample code is not working, Access to fetch from origin 'null' has been blocked by CORS policy

### ISSUE THREAD

**Issue by saidhn** [ashishagarwal2023/freegpt.js.org#2]
I used this sample code:

```
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Load from jsDelivr -->
<script src="https://cdn.jsdelivr.net/gh/ashishagarwal2023/freegptjs@1.0.2/src/freegpt.min.js"></script>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>My demo page</title>
</head>
<body>
<script>
(async () => {
  let response = await gpt.ask("Explain variables in javascript");
  console.log(response); // you got it!
})();
</script>
</body>
</html>

```
on my local pc chrome browser, but that did not work and got this javascript errors:
```
Access to fetch at 'https://you.com/api/streamingSearch?q=Explain%20variables%20in%20javascript&page=1&count=10&domain=youchat' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
freegpt.js:10 
        
        
       GET https://you.com/api/streamingSearch?q=Explain%20variables%20in%20javascript&page=1&count=10&domain=youchat net::ERR_FAILED 403 (Forbidden)
(anonymous) @ freegpt.js:10
ask @ freegpt.js:68
(anonymous) @ testGPT.html:13
(anonymous) @ testGPT.html:15
freegpt.js:15 Bot failed to fetch response: TypeError: Failed to fetch
    at freegpt.js:10:30
    at Object.ask (freegpt.js:68:18)
    at testGPT.html:13:28
    at testGPT.html:15:3
```
![image](https://github.com/ashishagarwal2023/freegpt.js.org/assets/42241963/4002ed5b-1609-422d-a9e7-7ac177ebbebd)

I think this is related to cloudflare protection. even with javascript client it still not working, is there anyway to bypass it?

**Comment by devashish2024** [comment]
Can you try the same thing on localhost or somewhere else? It would probably work.

Hint: CORS error will come from file://, so you need to use http:// or https://

**Comment by devashish2024** [comment]
I'm sure this resolsves the issue as long as my example (or my chatgpt clone) also works.

**Comment by devashish2024** [comment]
> I used this sample code:
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
> 
> <script src="https://cdn.jsdelivr.net/gh/ashishagarwal2023/freegptjs@1.0.2/src/freegpt.min.js"></script>
> <meta charset="UTF-8">
> <meta name="viewport" content="width=device-width, initial-scale=1.0">
> <title>My demo page</title>
> </head>
> <body>
> <script>
> (async () => {
>   let response = await gpt.ask("Explain variables in javascript");
>   console.log(response); // you got it!
> })();
> </script>
> </body>
> </html>
> ```
> 
> on my local pc chrome browser, but that did not work and got this javascript errors:
> 
> ```
> Access to fetch at 'https://you.com/api/streamingSearch?q=Explain%20variables%20in%20javascript&page=1&count=10&domain=youchat' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> freegpt.js:10 
>         
>         
>        GET https://you.com/api/streamingSearch?q=Explain%20variables%20in%20javascript&page=1&count=10&domain=youchat net::ERR_FAILED 403 (Forbidden)
> (anonymous) @ freegpt.js:10
> ask @ freegpt.js:68
> (anonymous) @ testGPT.html:13
> (anonymous) @ testGPT.html:15
> freegpt.js:15 Bot failed to fetch response: TypeError: Failed to fetch
>     at freegpt.js:10:30
>     at Object.ask (freegpt.js:68:18)
>     at testGPT.html:13:28
>     at testGPT.html:15:3
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/42241963/321927525-4002ed5b-1609-422d-a9e7-7ac177ebbebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTQxMDYsIm5iZiI6MTcxMjkxMzgwNiwicGF0aCI6Ii80MjI0MTk2My8zMjE5Mjc1MjUtNDAwMmVkNWItMTYwOS00MjJkLWE5ZTctN2FjMTc3ZWJiZWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA5MjMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MDEyMDdkZDVhNjVkODcxZGRmZjQxMjRiZjUyNWEyOTQ3OTg3MTRlOGE2YjUwODA3ZWRmM2VhNGI3NDNiNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iz9KNsT-UlY8xoy-YIpty5pe8oy-0fHKgDRTAM-gTtE)
> 
> I think this is related to cloudflare protection. even with javascript client it still not working, is there anyway to bypass it?

I gotta say, you ar using 1.0.2 but theres new version 1.0.3 (this repo waas named freegptjs but I renamed to freegpt.js.org) so you should update your code's <script> also to fetch from the new source.

The new source URL can be found in the readme, the documentation (freegpt.js.org) is a bit outdated I'll update it later.

_(however 1.0.3 is just a few changes and not a new feature that someone would probably want, you can skip update if you wish, the code will work same)_

**Comment by saidhn** [comment]
Thank you @ashishagarwal2023, it did work fine on the server with a domain.
