### ISSUE TITLE
I made an NodeJS version of your project

### ISSUE THREAD

**Issue by anil-turk** [ashishagarwal2023/freegpt.js.org#5]
[anil-turk/FreeGPT-NodeJS-PHP](https://github.com/anil-turk/FreeGPT-NodeJS-PHP) here is a working NodeJS version that can bypass the Cloudflare protection. If you want you can add to your readme for who want to use server-side.

**Comment by devashish2024** [comment]
Nice, I tried to make aswell, but it didn't work as it needed proxy. Nice, adding...

**Comment by devashish2024** [comment]
Added to README.

**Comment by anil-turk** [comment]
Well it works without proxy now Im using on my server. If you tell me more details I would be happy to help.

**Comment by anil-turk** [comment]
Mine works without proxy but I put an option in case of ip blocks. Thanks for your project as you can see I used your codes to develop.
